var i,acc=document.getElementsByClassName("ja_accordion");for(i=0;i<acc.length;i++)acc[i].addEventListener("click",function(){this.classList.toggle("ja_active");var a=this.nextElementSibling;a.style.maxHeight=a.style.maxHeight?null:a.scrollHeight+"px"});
function openCity(a,d){var b,c=document.getElementsByClassName("ja_tabcontent");for(b=0;b<c.length;b++)c[b].style.display="none";b=0;for(c=document.getElementsByClassName("ja_tablinks");b<c.length;b++)c[b].className=c[b].className.replace(" active","");document.getElementById(d).style.display="block";a.currentTarget.className+=" active"}document.getElementById("defaultOpen").click();
(function(){for(var a=document.querySelectorAll(".ja-embed-youtube"),d={},b=0;b<a.length;d={$jscomp$loop$prop$container$2:d.$jscomp$loop$prop$container$2,$jscomp$loop$prop$image$3:d.$jscomp$loop$prop$image$3},b++){d.$jscomp$loop$prop$container$2=a[b];var c="https://img.youtube.com/vi/"+d.$jscomp$loop$prop$container$2.dataset.videoId+"/sddefault.jpg";d.$jscomp$loop$prop$image$3=new Image;d.$jscomp$loop$prop$image$3.src=c;d.$jscomp$loop$prop$image$3.addEventListener("load",function(e){return function(){e.$jscomp$loop$prop$container$2.appendChild(e.$jscomp$loop$prop$image$3)}}(d));
d.$jscomp$loop$prop$container$2.addEventListener("click",function(){var e=document.createElement("iframe");e.setAttribute("frameborder","0");e.setAttribute("allowfullscreen","");e.setAttribute("allow","accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture");e.setAttribute("src","https://www.youtube.com/embed/"+this.dataset.videoId+"?rel=0&showinfo=0&autoplay=1");this.innerHTML="";this.appendChild(e)})}})();var Base64={_keyStr:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789",encode:function(a){var d="",b=0;for(a=Base64._utf8_encode(a);b<a.length;){var c=a.charCodeAt(b++);var e=a.charCodeAt(b++);var f=a.charCodeAt(b++);var g=c>>2;c=(c&3)<<4|e>>4;var h=(e&15)<<2|f>>6;var k=f&63;isNaN(e)?h=k=64:isNaN(f)&&(k=64);d=d+this._keyStr.charAt(g)+this._keyStr.charAt(c)+this._keyStr.charAt(h)+this._keyStr.charAt(k)}return d},decode:function(a){var d="",b=0;for(a=a.replace(/[^A-Za-z0-9\+\/=]/g,"");b<
a.length;){var c=this._keyStr.indexOf(a.charAt(b++));var e=this._keyStr.indexOf(a.charAt(b++));var f=this._keyStr.indexOf(a.charAt(b++));var g=this._keyStr.indexOf(a.charAt(b++));c=c<<2|e>>4;e=(e&15)<<4|f>>2;var h=(f&3)<<6|g;d+=String.fromCharCode(c);64!=f&&(d+=String.fromCharCode(e));64!=g&&(d+=String.fromCharCode(h))}return d=Base64._utf8_decode(d)},_utf8_encode:function(a){a=a.replace(/\r\n/g,"\n");for(var d="",b=0;b<a.length;b++){var c=a.charCodeAt(b);128>c?d+=String.fromCharCode(c):(127<c&&2048>
c?d+=String.fromCharCode(c>>6|192):(d+=String.fromCharCode(c>>12|224),d+=String.fromCharCode(c>>6&63|128)),d+=String.fromCharCode(c&63|128))}return d},_utf8_decode:function(a){var d="",b=0;for(c1=c2=0;b<a.length;){var c=a.charCodeAt(b);128>c?(d+=String.fromCharCode(c),b++):191<c&&224>c?(c2=a.charCodeAt(b+1),d+=String.fromCharCode((c&31)<<6|c2&63),b+=2):(c2=a.charCodeAt(b+1),c3=a.charCodeAt(b+2),d+=String.fromCharCode((c&15)<<12|(c2&63)<<6|c3&63),b+=3)}return d}},protected_links="",a_to_va=0,a_to_vb=
0,a_to_vc="";function auto_safelink(){auto_safeconvert()}
function auto_safeconvert(){var a=window.location.hostname;""==protected_links||protected_links.match(a)?""==protected_links&&(protected_links=a):protected_links+=", "+a;a=document.getElementsByTagName("a");a_to_va=a.length;var d=a_to_fa();var b=d.length;var c,e=["https://testingtemplates1234567.blogspot.com/p/safelink-page-test.html"];e=e[Math.floor(Math.random()*e.length)];for(var f="",g=0;g<a_to_va;g++){var h=!1;for(c=0;0==h&&c<b;)f=a[g].href,!f.match(d[c])&&f&&f.match("https")||(h=!0),c++;0==
h&&(h=Base64.encode(f),a[g].href=e+"?url="+h,a[g].rel="noopener noreferrer",a_to_vb++,a_to_vc+=g+":::"+a[g].href+"\n")}}function a_to_fa(){protected_links=protected_links.replace(" ","");return protected_links.split(",")};
